import { Profile, TopRepos } from "@/components";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  keywords: "nextjs, react, typescript",
};

export default function Home() {
  return (
    <main className="w-full max-w-7xl flex-1 self-center p-2">
      <div className="flex items-start gap-8 pt-4">
        <Profile />
        <TopRepos />
      </div>
    </main>
  );
}
