import { Profile, TopRepos } from "@/components";
import { getProfile, getRepos } from "@/utils/dataFetchers";
import { notFound } from "next/navigation";

export const revalidate = 60;

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  keywords: "nextjs, react, typescript",
};

export default async function Home() {
  const profileData = getProfile();
  const reposData = getRepos();

  const [profile, repos] = await Promise.all([profileData, reposData]);
  if (!profile || !repos) notFound();
  return (
    <div className="flex-1 p-2">
      <div className="flex items-start gap-8 pt-4">
        <Profile profile={profile} />
        <TopRepos repos={repos} />
      </div>
    </div>
  );
}
